# Generated by Django 5.2.4 on 2025-11-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={
                "default_permissions": [],
                "permissions": [("manage_promotions", "Can manage promotions")],
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
            },
        ),
        migrations.AlterModelOptions(
            name="couponassignment",
            options={
                "default_permissions": [],
                "verbose_name": "Asignación de Cupón",
                "verbose_name_plural": "Asignaciones de Cupones",
            },
        ),
        migrations.AlterModelOptions(
            name="couponusage",
            options={"default_permissions": []},
        ),
    ]
