# Generated by Django 5.2.4 on 2026-01-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_order_seller_alter_order_client"),
        (
            "promotions",
            "0002_alter_coupon_options_alter_couponassignment_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponusage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_usages",
                to="core.order",
            ),
        ),
    ]
