# Generated by Django 5.2.4 on 2025-09-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_currency_payment_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("zelle", "Zelle"),
                    ("wallet", "Wallet"),
                    ("enzona", "EnZona"),
                    ("transfermovil", "Transfermovil"),
                ],
                max_length=20,
            ),
        ),
    ]
