# Generated by Django 5.2.4 on 2025-10-03 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "logo_payment_method",
                    models.ImageField(
                        blank=True,
                        default="payment_methods/payment_method_default.png",
                        null=True,
                        upload_to="payment_methods/pics",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.paymentmethod",
            ),
        ),
    ]
