# Generated by Django 5.2.4 on 2025-10-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_paymentmethod_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="code_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
