# Generated by Django 5.2.4 on 2025-10-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_measurement_unit_options_and_more"),
        ("payments", "0005_paymentmethod_code_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="exchange_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="exchange_rate_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_methods",
                to="core.currency",
            ),
        ),
    ]
