# Generated by Django 5.2.4 on 2025-10-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_payment_exchange_rate_alter_wallet_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
