# Generated by Django 5.2.4 on 2025-10-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_order_delivery_address"),
        ("payments", "0009_alter_payment_exchange_rate_alter_wallet_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="core.order",
            ),
        ),
    ]
