# Generated by Django 5.2.4 on 2025-10-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_alter_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="use_in_pos",
            field=models.BooleanField(default=False),
        ),
    ]
