# Generated by Django 5.2.4 on 2025-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_paymentmethod_use_in_pos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionlog",
            name="transaction_type",
        ),
        migrations.RenameField(
            model_name="transactionlog",
            old_name="payment_date",
            new_name="transaction_log_date",
        ),
        migrations.RemoveField(
            model_name="transactionlog",
            name="amount_paid",
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="payment_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="TransactionType",
        ),
    ]
