# Generated by Django 5.2.4 on 2025-10-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_transactionlog_charge_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="ecommerce_commission_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="ecommerce_commission_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="ecommerce_commission_percentage",
            field=models.BooleanField(default=True),
        ),
    ]
