# Generated by Django 5.2.4 on 2025-10-15 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_payment_ecommerce_commission_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="client",
        ),
        migrations.AddField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                default=4,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
