# Generated by Django 5.2.4 on 2025-10-15 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_order_options"),
        ("payments", "0015_remove_wallet_client_wallet_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionlog",
            old_name="transaction_log_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="WalletOperationalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "previous_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("exchange_rate_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_logs",
                        to="core.currency",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_logs",
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Operational Log",
                "verbose_name_plural": "Wallet Operational Logs",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
