# Generated by Django 5.2.4 on 2025-10-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_walletoperationallog_charge_for_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
