# Generated by Django 5.2.4 on 2025-11-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_specificationdetails_product_and_more"),
        ("payments", "0018_payment_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["order"], name="payments_pa_order_i_1d1c93_idx"),
        ),
    ]
