# Generated by Django 5.2.4 on 2025-11-01 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_specificationdetails_product_and_more"),
        ("payments", "0019_payment_payments_pa_order_i_1d1c93_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_order_i_1d1c93_idx",
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "-created_at"], name="payments_pa_order_i_288dd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["user", "-created_at"], name="payments_wa_user_id_e3342b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletoperationallog",
            index=models.Index(
                fields=["wallet", "-created_at"], name="payments_wa_wallet__d75a19_idx"
            ),
        ),
    ]
