# Generated by Django 5.2.4 on 2025-11-05 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_remove_payment_payments_pa_order_i_1d1c93_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
