# Generated by Django 5.2.4 on 2025-12-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0021_paymentmethod_created_at_paymentmethod_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="url",
        ),
    ]
