# Generated by Django 5.2.4 on 2026-01-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_order_amount_order_credit_amount_and_more"),
        ("payments", "0022_remove_paymentmethod_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="core.order",
            ),
        ),
    ]
