# Generated by Django 5.2.4 on 2026-02-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0023_alter_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="use_in_store",
            field=models.BooleanField(default=False),
        ),
    ]
