# Generated by Django 5.2.4 on 2026-02-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0024_paymentmethod_use_in_store"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "permissions": [
                    ("manage_payment_methos", "Can manage payment methods")
                ],
            },
        ),
    ]
