# Generated by Django 5.2.4 on 2026-02-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0025_alter_paymentmethod_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "permissions": [
                    ("manage_payment_methods", "Can manage payment methods")
                ],
            },
        ),
    ]
