# Generated by Django 5.2.4 on 2025-09-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_product_custom_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Carrier",
                "verbose_name_plural": "Carriers",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "shipping_method_type",
                    models.CharField(
                        choices=[("standard", "Estándar"), ("express", "Express")],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_methods",
                        to="delivery.carrier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Method",
                "verbose_name_plural": "Shipping Methods",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated_delivery_time", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "shipping_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="method_shipping_rates",
                        to="delivery.shippingmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Rate",
                "verbose_name_plural": "Shipping Rates",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="OrderShipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping",
                        to="core.order",
                    ),
                ),
                (
                    "shipping_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_shippings",
                        to="delivery.shippingrate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Shipping",
                "verbose_name_plural": "Order Shippings",
                "ordering": ["-id"],
                "permissions": [("manage_delivery", "Can manage delivery")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "municipalities",
                    models.ManyToManyField(
                        related_name="shipping_zones", to="core.municipality"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="shipping_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zone_shipping_rates",
                to="delivery.shippingzone",
            ),
        ),
    ]
