# Generated by Django 5.2.4 on 2025-09-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingmethod",
            old_name="is_active",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="shippingrate",
            old_name="is_active",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="shippingzone",
            old_name="is_active",
            new_name="active",
        ),
    ]
