# Generated by Django 5.2.4 on 2025-09-27 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_rename_is_active_shippingmethod_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingmethod",
            name="carrier",
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="deliverers",
            field=models.ManyToManyField(
                related_name="shipping_zones", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Carrier",
        ),
    ]
