# Generated by Django 5.2.4 on 2025-10-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_remove_shippingmethod_carrier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordershipping",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="shippingrate",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
