# Generated by Django 5.2.4 on 2025-10-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_alter_ordershipping_price_alter_shippingrate_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordershipping",
            old_name="price",
            new_name="shipping_price",
        ),
        migrations.AddField(
            model_name="ordershipping",
            name="delivery_address",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
