# Generated by Django 5.2.4 on 2025-10-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_ordershipping_deliver_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordershipping",
            old_name="deliver",
            new_name="deliverer",
        ),
    ]
