# Generated by Django 5.2.4 on 2025-11-01 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_cart_core_cart_client__17074d_idx_and_more"),
        ("delivery", "0007_rename_deliver_ordershipping_deliverer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ordershipping",
            index=models.Index(
                fields=["deliverer", "shipped_at"],
                name="delivery_or_deliver_f8210d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordershipping",
            index=models.Index(
                fields=["shipped_at", "delivered_at"],
                name="delivery_or_shipped_22f082_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordershipping",
            index=models.Index(
                fields=["estimated_delivery_at"], name="delivery_or_estimat_09b62f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordershipping",
            index=models.Index(
                fields=["delivered_at"], name="delivery_or_deliver_76e796_idx"
            ),
        ),
    ]
