# Generated by Django 5.2.4 on 2025-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0008_ordershipping_delivery_or_deliver_f8210d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingzone",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
