# Generated by Django 5.2.4 on 2025-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0009_shippingzone_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
