# Generated by Django 5.2.4 on 2025-11-05 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0011_shippingrate_created_at_shippingrate_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordershipping",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordershipping",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
