# Generated by Django 5.2.4 on 2026-02-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0012_ordershipping_created_at_ordershipping_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingmethod",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_shipping_methods", "Can manage shipping methods")
                ],
                "verbose_name": "Shipping Method",
                "verbose_name_plural": "Shipping Methods",
            },
        ),
        migrations.AlterModelOptions(
            name="shippingzone",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [("manage_shipping_zones", "Can manage shipping zones")],
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
            },
        ),
    ]
