# Generated by Django 5.2.4 on 2026-02-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0013_alter_shippingmethod_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingrate",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [("manage_shipping_rates", "Can manage shipping rates")],
                "verbose_name": "Shipping Rate",
                "verbose_name_plural": "Shipping Rates",
            },
        ),
    ]
