# Generated by Django 5.2.4 on 2026-09-18 18:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "business_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_nit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_licence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("business_schedule", models.TextField(blank=True, null=True)),
                ("business_address", models.TextField(blank=True, null=True)),
                ("social_networks", models.JSONField(blank=True, default=list)),
                ("backend_url", models.CharField(default="", max_length=255)),
                ("front_url", models.CharField(default="", max_length=255)),
                ("recover_password_url", models.CharField(default="", max_length=255)),
                ("login_url", models.CharField(default="", max_length=255)),
                ("confirm_register_url", models.CharField(default="", max_length=255)),
                (
                    "recover_password_token_validation_time",
                    models.IntegerField(default=30),
                ),
                (
                    "ecommerce_commission_is_percentage",
                    models.BooleanField(default=True),
                ),
                (
                    "ecommerce_commission_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "client_minimum_wallet_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=10
                    ),
                ),
                ("billing_email", models.TextField(blank=True, null=True)),
                (
                    "logo_light",
                    models.ImageField(
                        default="config/config_image_default.png",
                        upload_to="config/pics",
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        default="config/config_image_default.png",
                        upload_to="config/pics",
                    ),
                ),
                (
                    "logo_horizontal_light",
                    models.ImageField(
                        default="config/config_image_default.png",
                        upload_to="config/pics",
                    ),
                ),
                (
                    "logo_horizontal_dark",
                    models.ImageField(
                        default="config/config_image_default.png",
                        upload_to="config/pics",
                    ),
                ),
                (
                    "admin_logo_horizontal_light",
                    models.ImageField(
                        default="config/config_image_default.png",
                        upload_to="config/pics",
                    ),
                ),
                (
                    "admin_logo_horizontal_dark",
                    models.ImageField(
                        default="config/config_image_default.png",
                        upload_to="config/pics",
                    ),
                ),
                (
                    "waha_api_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "waha_api_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "waha_api_apikey",
                    models.CharField(
                        blank=True, default="admin", max_length=255, null=True
                    ),
                ),
                (
                    "waha_api_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "waha_api_session",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "enzona_api_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "enzona_consumer_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "enzona_consumer_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transfermovil_api_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transfermovil_callback_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transfermovil_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transfermovil_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transfermovil_seed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tropipay_api_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tropipay_client_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tropipay_client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tropipay_paymentcards_account_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "mqtt_client_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mqtt_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mqtt_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mqtt_host", models.CharField(blank=True, max_length=255, null=True)),
                ("mqtt_port", models.IntegerField(blank=True, null=True)),
                (
                    "mqtt_location_topic",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "astrack_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "astrack_websocket",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("astrack_token", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
                "ordering": ["-id"],
                "permissions": [("manage_config", "Can manage configuration")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ContainerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("free_days", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Container Type",
                "verbose_name_plural": "Container Types",
                "ordering": ["name"],
                "permissions": [
                    ("manage_container_types", "Can manage container types")
                ],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code_alpha3", models.CharField(max_length=3)),
                (
                    "country_flag",
                    models.ImageField(
                        blank=True,
                        default="flags/flag_image_default.png",
                        null=True,
                        upload_to="flags/pics",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
                "permissions": [("manage_country", "Can manage country")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("initials", models.CharField(max_length=5)),
                ("symbol", models.CharField(max_length=1)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("exchange_rate_date", models.DateTimeField(auto_now=True)),
                ("default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["-id"],
                "permissions": [("manage_currencies", "Can manage currencies")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Measurement_Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("abbreviation", models.CharField(max_length=3)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Measurement Unit",
                "verbose_name_plural": "Measurement Units",
                "ordering": ["name"],
                "permissions": [
                    ("manage_measurement_unit", "Can manage measurement unit")
                ],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Notification Type",
                "verbose_name_plural": "Notification Types",
                "ordering": ["name"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Port",
                "verbose_name_plural": "Ports",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ProcessingPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phytosanitary_permit", models.BooleanField(default=False)),
                (
                    "phytosanitary_permit_expires",
                    models.DateField(blank=True, null=True),
                ),
                ("veterinary_permit", models.BooleanField(default=False)),
                ("veterinary_permit_expires", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Processing Plant",
                "verbose_name_plural": "Processing Plants",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_sku", models.CharField(blank=True, max_length=255, unique=True)),
                ("part_code", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(max_length=1024)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "net_content",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "quantity_per_box",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("use_custom_template", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("custom_template", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["code_sku"],
                "permissions": [("manage_product", "Can manage product")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ProductImageOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ["name"],
                "permissions": [("manage_provider", "Can manage provider")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=100)),
                ("po_date", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "ordering": ["-po_date"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="SaleOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_number", models.CharField(max_length=100)),
                ("so_date", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sale Order",
                "verbose_name_plural": "Sale Orders",
                "ordering": ["-so_date"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ShippingCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Shipping Company",
                "verbose_name_plural": "Shipping Companies",
                "ordering": ["name"],
                "permissions": [
                    ("manage_shipping_companies", "Can manage shipping companies")
                ],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="SpecificationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Specification Detail",
                "verbose_name_plural": "Specification Details",
                "ordering": ["id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Specifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Specification",
                "verbose_name_plural": "Specifications",
                "ordering": ["id"],
                "permissions": [("manage_specifications", "Can manage specifications")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Vessel",
                "verbose_name_plural": "Vessels",
                "ordering": ["name"],
                "permissions": [("manage_vessels", "Can manage vessels")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo_brand",
                    models.ImageField(
                        blank=True,
                        default="brands/brand_image_default.png",
                        null=True,
                        upload_to="brands/pics",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brand",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
                "permissions": [("manage_brand", "Can manage brand")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category_image",
                    models.ImageField(
                        blank=True,
                        default="categories/category_image_default.png",
                        null=True,
                        upload_to="categories/pics",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["id"],
                "permissions": [("manage_category", "Can manage category")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Incoterms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Incoterms",
                "verbose_name_plural": "Incoterms",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
                "indexes": [
                    models.Index(
                        fields=["abbreviation"], name="core_incote_abbrevi_82723b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=1024)),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="core.notificationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-id"],
                "permissions": [("manage_notification", "Can manage notification")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="NotificationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications_user",
                        to="core.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification",
                "verbose_name_plural": "User Notifications",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
