# Generated by Django 5.2.4 on 2026-09-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_number", models.CharField(max_length=30)),
                ("voyage_number", models.CharField(blank=True, max_length=20)),
                ("cut_off", models.DateField(blank=True, null=True)),
                ("ets", models.DateField(blank=True, null=True)),
                ("eta", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "port_discharge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="port_discharge",
                        to="core.port",
                    ),
                ),
                (
                    "port_loading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="port_loading",
                        to="core.port",
                    ),
                ),
                (
                    "shiping_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="core.shippingcompany",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="core.vessel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-id"],
                "permissions": [("manage_bookings", "Can manage bookings")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.AlterField(
            model_name="shippingcompanyinvoice",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_company_invoice",
                to="core.booking",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_number"], name="core_bookin_booking_2e4e10_idx"
            ),
        ),
    ]
