# Generated by Django 5.2.4 on 2026-09-18 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="port",
            index=models.Index(
                fields=["abbreviation"], name="core_port_abbrevi_f76af2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingplant",
            index=models.Index(fields=["name"], name="core_proces_name_c5d026_idx"),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="measurement_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.measurement_unit",
            ),
        ),
        migrations.AddField(
            model_name="productimageorder",
            name="blockmedia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cms.blockmedia"
            ),
        ),
        migrations.AddField(
            model_name="productimageorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_images",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="core.ProductImageOrder",
                to="cms.blockmedia",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.provider",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="measurement_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="core.measurement_unit",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="core.product",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="core.provider",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="arrival_port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival_sale_orders",
                to="core.port",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="incoterms",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_orders",
                to="core.incoterms",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="processing_plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_orders",
                to="core.processingplant",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_orders",
                to="core.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="shipment_port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipment_sale_orders",
                to="core.port",
            ),
        ),
        migrations.AddField(
            model_name="specificationdetails",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications_details",
                to="core.product",
            ),
        ),
        migrations.AddField(
            model_name="specificationdetails",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications_details",
                to="core.specifications",
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="shipping_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vessels",
                to="core.shippingcompany",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationuser",
            index=models.Index(fields=["user"], name="core_notifi_user_id_b22395_idx"),
        ),
        migrations.AddIndex(
            model_name="productimageorder",
            index=models.Index(
                fields=["product", "id"], name="core_produc_product_49f199_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productimageorder",
            unique_together={("product", "blockmedia")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "active"], name="core_produc_categor_0a9d66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["part_code", "active"], name="core_produc_part_co_4d7c25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "active"], name="core_produc_brand_i_5a64b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["provider", "active"], name="core_produc_provide_91235b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["po_number"], name="core_purcha_po_numb_14c4ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleorder",
            index=models.Index(
                fields=["so_number"], name="core_saleor_so_numb_076461_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specificationdetails",
            index=models.Index(
                fields=["product"], name="core_specif_product_f34eef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specificationdetails",
            index=models.Index(
                fields=["product", "specification"],
                name="core_specif_product_0d7bb4_idx",
            ),
        ),
    ]
