# Generated by Django 5.2.4 on 2026-09-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_booking_alter_shippingcompanyinvoice_booking_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="shiping_company",
            new_name="shipping_company",
        ),
    ]
