# Generated by Django 5.2.4 on 2026-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="port",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
