# Generated by Django 5.2.4 on 2026-10-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_productprovider_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productprovider",
            unique_together={("product", "provider")},
        ),
    ]
