# Generated by Django 5.2.4 on 2025-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="custom_template",
            field=models.BooleanField(default=False),
        ),
    ]
