# Generated by Django 5.2.4 on 2026-10-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_shippingcompanyinvoice_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tariff_item",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="CustomerInvoice",
            fields=[
                (
                    "invoice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.invoice",
                    ),
                ),
                ("contract", models.CharField(max_length=50)),
                (
                    "commercial_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_invoices",
                        to="core.booking",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_invoices",
                        to="core.customer",
                    ),
                ),
                (
                    "incoterms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_invoices",
                        to="core.incoterms",
                    ),
                ),
            ],
            bases=("core.invoice",),
        ),
        migrations.AddField(
            model_name="container",
            name="customer_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="containers",
                to="core.customerinvoice",
            ),
        ),
        migrations.CreateModel(
            name="CustomerInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "customer_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_items",
                        to="core.customerinvoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.productproviderpresentation",
                    ),
                ),
            ],
        ),
    ]
