# Generated by Django 5.2.4 on 2026-10-02 13:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_tariff_item_customerinvoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cargo_insurance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
