# Generated by Django 5.2.4 on 2025-09-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_custom_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="config",
            old_name="logo",
            new_name="logo_dark",
        ),
        migrations.AddField(
            model_name="config",
            name="logo_light",
            field=models.ImageField(
                default="config/config_image_default.png", upload_to="config/pics"
            ),
        ),
    ]
