# Generated by Django 5.2.4 on 2026-10-01 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_tariff_item_customerinvoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="providers",
                to="core.country",
            ),
        ),
    ]
