# Generated by Django 5.2.4 on 2026-09-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_shiping_company_booking_shipping_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("seal_number", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Container",
                "verbose_name_plural": "Containers",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.AlterModelOptions(
            name="providerinvoice",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Provider Invoice",
                "verbose_name_plural": "Provider Invoices",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["bill_number"], name="core_invoic_bill_nu_753f6b_idx"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="containers",
                to="core.booking",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="container_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="containers",
                to="core.containertype",
            ),
        ),
    ]
