# Generated by Django 5.2.4 on 2026-09-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_port_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incoterms",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [("manage_incoterms", "Can manage incoterms")],
                "verbose_name": "Incoterms",
                "verbose_name_plural": "Incoterms",
            },
        ),
        migrations.AlterModelOptions(
            name="port",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [("manage_ports", "Can manage ports")],
                "verbose_name": "Port",
                "verbose_name_plural": "Ports",
            },
        ),
        migrations.AlterModelOptions(
            name="processingplant",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_processing_plants", "Can manage processing plant")
                ],
                "verbose_name": "Processing Plant",
                "verbose_name_plural": "Processing Plants",
            },
        ),
    ]
