# Generated by Django 5.2.4 on 2026-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_productprovider_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="productproviderpresentation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productproviderpresentation",
            name="presentations",
            field=models.ManyToManyField(to="core.presentation"),
        ),
    ]
