# Generated by Django 5.2.4 on 2025-09-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_logo_config_logo_dark_config_logo_light"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TransactionLog",
        ),
        migrations.DeleteModel(
            name="TransactionType",
        ),
    ]
