# Generated by Django 5.2.4 on 2026-09-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_incoterms_options_alter_port_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="wholesale_price",
        ),
    ]
