# Generated by Django 5.2.4 on 2026-10-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_productproviderpresentation_description_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productproviderpresentation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="productproviderpresentation",
            name="presentation",
        ),
    ]
