# Generated by Django 5.2.4 on 2026-09-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_container_alter_providerinvoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="discharge_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="extraction_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="net_weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="container",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containers",
                to="core.booking",
            ),
        ),
    ]
