# Generated by Django 5.2.4 on 2026-10-01 22:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_provider_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerinvoice",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Customer Invoice",
                "verbose_name_plural": "Customer Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="customerinvoiceitem",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Customer Invoice Item",
                "verbose_name_plural": "Customer Invoice Items",
            },
        ),
        migrations.AlterField(
            model_name="customerinvoiceitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
