# Generated by Django 5.2.4 on 2026-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_customerinvoice_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportingCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "phone_numbers",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("web_site", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Importing Company",
                "verbose_name_plural": "Importing Companies",
                "ordering": ["-id"],
                "permissions": [
                    ("manage_importing_companies", "Can manage importing companies")
                ],
                "abstract": False,
                "default_permissions": [],
                "indexes": [
                    models.Index(fields=["name"], name="core_import_name_c27206_idx")
                ],
            },
        ),
    ]
