# Generated by Django 5.2.4 on 2025-09-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_transactionlog_delete_transactiontype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("initials", models.CharField(max_length=5)),
                ("symbol", models.CharField(max_length=1)),
                ("exchange_rate", models.FloatField(default=0)),
                ("exchange_rate_date", models.DateTimeField(auto_now=True)),
                ("default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["-id"],
                "permissions": [("manage_currencies", "Can manage currencies")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
