# Generated by Django 5.2.4 on 2026-09-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_product_wholesale_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Presentation",
                "verbose_name_plural": "Presentations",
                "ordering": ["-id"],
                "permissions": [("manage_presentation", "Can manage presentation")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ProductPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presentation",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="core.presentation"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.product"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.provider"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
