# Generated by Django 5.2.4 on 2026-09-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_container_discharge_date_container_extraction_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="sale_orders",
            field=models.ManyToManyField(
                blank=True, related_name="container_items", to="core.saleorder"
            ),
        ),
        migrations.CreateModel(
            name="ContainerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.container",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="container_items",
                        to="core.productproviderpresentation",
                    ),
                ),
            ],
        ),
    ]
