# Generated by Django 5.2.4 on 2026-10-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_booking_cargo_insurance"),
        ("core", "0005_alter_customerinvoice_options_and_more"),
    ]

    operations = []
