# Generated by Django 5.2.4 on 2026-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_productproviderpresentation_unique_together_and_more"),
        ("file_manager", "0004_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="files",
            field=models.ManyToManyField(to="file_manager.file"),
        ),
        migrations.AddField(
            model_name="container",
            name="files",
            field=models.ManyToManyField(to="file_manager.file"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="files",
            field=models.ManyToManyField(to="file_manager.file"),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="files",
            field=models.ManyToManyField(to="file_manager.file"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="files",
            field=models.ManyToManyField(to="file_manager.file"),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="files",
            field=models.ManyToManyField(to="file_manager.file"),
        ),
    ]
