# Generated by Django 5.2.4 on 2026-10-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_importingcompany"),
        ("core", "0006_merge_20261002_1006"),
    ]

    operations = []
