# Generated by Django 5.2.4 on 2025-09-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="commercial_name",
        ),
    ]
