# Generated by Django 5.2.4 on 2026-10-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_booking_files_container_files_invoice_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Activo"),
                    ("ready_to_ship", "Listo para salir"),
                    ("in_transit", "En tránsito"),
                    ("arrived", "Arribado"),
                    ("canceled", "Cancelado"),
                ],
                default="active",
                max_length=50,
            ),
        ),
    ]
