# Generated by Django 5.2.4 on 2026-09-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_container_sale_orders_containeritem"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="sale_orders",
            field=models.ManyToManyField(
                blank=True, related_name="bookings", to="core.saleorder"
            ),
        ),
    ]
