# Generated by Django 5.2.4 on 2026-09-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_presentation_productpresentation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productpresentation",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Product - Presentation",
                "verbose_name_plural": "Product - Presentations",
            },
        ),
    ]
