# Generated by Django 5.2.4 on 2026-10-02 15:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20261002_1006"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saleorderitems",
            old_name="unit_weight",
            new_name="unit_gross_weight",
        ),
        migrations.AddField(
            model_name="customerinvoiceitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="customerinvoiceitem",
            name="gross_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="customerinvoiceitem",
            name="measurement_unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.measurement_unit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customerinvoiceitem",
            name="net_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="customerinvoiceitem",
            name="unit_gross_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="customerinvoiceitem",
            name="unit_net_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="saleorderitems",
            name="unit_net_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
