# Generated by Django 5.2.4 on 2025-09-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_category_commercial_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="commercial_name",
        ),
    ]
