# Generated by Django 5.2.4 on 2026-09-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_booking_sale_orders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="sale_orders",
        ),
    ]
