# Generated by Django 5.2.4 on 2026-09-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_productpresentation_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.product"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.provider"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product - Presentation",
                "verbose_name_plural": "Product - Presentations",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ProductProviderPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.presentation",
                    ),
                ),
                (
                    "product_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.productprovider",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProductPresentation",
        ),
    ]
