# Generated by Django 5.2.4 on 2026-10-02 16:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_unit_weight_saleorderitems_unit_gross_weight_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="containeritem",
            old_name="unit_weight",
            new_name="unit_gross_weight",
        ),
        migrations.AddField(
            model_name="containeritem",
            name="unit_net_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
