# Generated by Django 5.2.4 on 2026-09-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_productprovider_productproviderpresentation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productproviderpresentation",
            name="presentation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_providers",
                to="core.presentation",
            ),
        ),
    ]
