# Generated by Django 5.2.4 on 2026-09-25 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_container_sale_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="containeritem",
            name="sale_order_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="container_items",
                to="core.saleorderitems",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="containeritem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="containeritem",
            name="unit_weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
