# Generated by Django 5.2.4 on 2026-10-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_merge_0006_importingcompany_0006_merge_20261002_1006"),
        ("core", "0008_rename_unit_weight_containeritem_unit_gross_weight_and_more"),
    ]

    operations = []
