# Generated by Django 5.2.4 on 2026-10-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_merge_20261002_1310"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="container",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [("manage_containers", "Can manage containers")],
                "verbose_name": "Container",
                "verbose_name_plural": "Containers",
            },
        ),
        migrations.AlterModelOptions(
            name="customerinvoice",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_customer_invoices", "Can manage customer invoices")
                ],
                "verbose_name": "Customer Invoice",
                "verbose_name_plural": "Customer Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="invoicepayment",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_invoice_payments", "Can manage invoice payments")
                ],
                "verbose_name": "Invoice Payment",
                "verbose_name_plural": "Invoice Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="providerinvoice",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_provider_invoices", "Can manage provider invoices")
                ],
                "verbose_name": "Provider Invoice",
                "verbose_name_plural": "Provider Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="shippingcompanyinvoice",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    (
                        "manage_shipping_company_invoices",
                        "Can manage shipping company invoices",
                    )
                ],
                "verbose_name": "Shipping Company Invoice",
                "verbose_name_plural": "Shipping Company Invoices",
            },
        ),
    ]
