# Generated by Django 5.2.4 on 2025-10-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_order_delivery_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity_contained",
            new_name="net_content",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity_per_pallets",
        ),
    ]
