# Generated by Django 5.2.4 on 2026-09-26 13:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_containeritem_sale_order_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="containeritem",
            name="sale_order_item",
        ),
        migrations.AddField(
            model_name="booking",
            name="quoted_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="sale_orders",
            field=models.ManyToManyField(
                blank=True, related_name="container_items", to="core.saleorder"
            ),
        ),
        migrations.AddField(
            model_name="shippingcompanyinvoice",
            name="bl_number",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="container",
            name="net_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="pending_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="invoicepayment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["ets"], name="core_bookin_ets_b9b692_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["eta"], name="core_bookin_eta_5c1e6f_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["shipping_company", "ets"],
                name="core_bookin_shippin_3ac9b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["shipping_company", "eta"],
                name="core_bookin_shippin_74f6b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["discharge_date"], name="core_contai_dischar_c5f30d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["booking", "discharge_date"],
                name="core_contai_booking_5ddf3a_idx",
            ),
        ),
    ]
