# Generated by Django 5.2.4 on 2026-09-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_productproviderpresentation_presentation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productproviderpresentation",
            name="product_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.productprovider"
            ),
        ),
    ]
