# Generated by Django 5.2.4 on 2025-10-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_quantity_contained_product_net_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "permissions": [("manage_brand", "Can manage brand")],
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "permissions": [("manage_country", "Can manage country")],
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "default_permissions": [],
                "ordering": ["code_sku"],
                "permissions": [("manage_product", "Can manage product")],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
