# Generated by Django 5.2.4 on 2026-09-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_productproviderpresentation_product_provider"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productprovider",
            unique_together={("product", "provider")},
        ),
        migrations.AlterUniqueTogether(
            name="productproviderpresentation",
            unique_together={("product_provider", "presentation")},
        ),
    ]
