# Generated by Django 5.2.4 on 2026-10-02 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_container_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="containeritem",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Container Item",
                "verbose_name_plural": "Container Items",
            },
        ),
        migrations.AddIndex(
            model_name="containeritem",
            index=models.Index(
                fields=["container", "product"], name="core_contai_contain_4764e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="containeritem",
            index=models.Index(
                fields=["container", "product", "sale_order_item"],
                name="core_contai_contain_8f851f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerinvoice",
            index=models.Index(
                fields=["customer"], name="core_custom_custome_744417_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerinvoiceitem",
            index=models.Index(
                fields=["customer_invoice", "product"],
                name="core_custom_custome_81e9a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoicepayment",
            index=models.Index(
                fields=["invoice", "payment_date"],
                name="core_invoic_invoice_d72133_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoicepayment",
            index=models.Index(
                fields=["user", "payment_date"], name="core_invoic_user_id_205cb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingcompanyinvoice",
            index=models.Index(
                fields=["booking"], name="core_shippi_booking_68c705_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingcompanyinvoice",
            index=models.Index(
                fields=["bl_number"], name="core_shippi_bl_numb_821810_idx"
            ),
        ),
    ]
