# Generated by Django 5.2.4 on 2026-10-02 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
        ("core", "0011_alter_containeritem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productproviderpresentation",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Product Provider Presentation",
                "verbose_name_plural": "Product Provider Presentations",
            },
        ),
        migrations.RemoveIndex(
            model_name="importingcompany",
            name="core_import_name_c27206_idx",
        ),
        migrations.RemoveIndex(
            model_name="port",
            name="core_port_abbrevi_f76af2_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="core_produc_part_co_4d7c25_idx",
        ),
        migrations.RemoveIndex(
            model_name="productimageorder",
            name="core_produc_product_49f199_idx",
        ),
        migrations.RemoveIndex(
            model_name="saleorder",
            name="core_saleor_so_numb_076461_idx",
        ),
        migrations.RemoveField(
            model_name="config",
            name="client_minimum_wallet_amount",
        ),
        migrations.RemoveField(
            model_name="config",
            name="ecommerce_commission_is_percentage",
        ),
        migrations.RemoveField(
            model_name="config",
            name="ecommerce_commission_value",
        ),
        migrations.AddField(
            model_name="customer",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["business_name"], name="core_custom_busines_0903cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="port",
            index=models.Index(
                fields=["abbreviation", "active"], name="core_port_abbrevi_28a721_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tariff_item", "active"], name="core_produc_tariff__529893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimageorder",
            index=models.Index(
                fields=["product"], name="core_produc_product_fd8127_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerinvoice",
            index=models.Index(
                fields=["sale_order"], name="core_provid_sale_or_f895f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["customer", "provider"], name="core_purcha_custome_b00c04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(
                fields=["purchase_order", "product"],
                name="core_purcha_purchas_b7503d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleorder",
            index=models.Index(
                fields=["customer", "so_number"], name="core_saleor_custome_719b24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleorderitems",
            index=models.Index(
                fields=["sale_order", "product"], name="core_saleor_sale_or_182a38_idx"
            ),
        ),
    ]
