# Generated by Django 5.2.4 on 2026-09-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_invoice_amount_invoice_other_charges_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="sale_orders",
        ),
        migrations.AddField(
            model_name="containeritem",
            name="sale_order_item",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="container_items",
                to="core.saleorderitems",
            ),
            preserve_default=False,
        ),
    ]
