# Generated by Django 5.2.4 on 2025-10-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_brand_options_alter_country_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="confirm_register_url",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
