# Generated by Django 5.2.4 on 2026-09-20 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_productprovider_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "default_permissions": [],
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
            },
        ),
        migrations.RemoveIndex(
            model_name="purchaseorder",
            name="core_purcha_po_numb_14c4ab_idx",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="measurement_unit",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="po_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="po_number",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="product",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="quantity",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="observations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="core.provider",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="measurement_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.measurement_unit"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_items",
                to="core.productproviderpresentation",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_items",
                to="core.purchaseorder",
            ),
        ),
    ]
