# Generated by Django 5.2.4 on 2026-09-26 16:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_container_sale_orders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="gross_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
