# Generated by Django 5.2.4 on 2026-09-21 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_purchaseorderitem_alter_purchaseorder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_items",
                to="core.purchaseorder",
            ),
        ),
    ]
