# Generated by Django 5.2.4 on 2025-10-05 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_config_confirm_register_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement_unit",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "permissions": [
                    ("manage_measurement_unit", "Can manage measurement unit")
                ],
                "verbose_name": "Measurement Unit",
                "verbose_name_plural": "Measurement Units",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationtype",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "verbose_name": "Notification Type",
                "verbose_name_plural": "Notification Types",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "permissions": [("manage_provider", "Can manage provider")],
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.AlterField(
            model_name="contactaddress",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="addresses",
                to="core.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(
                related_name="products", to="core.specificationdetails"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="core.product",
            ),
        ),
    ]
