# Generated by Django 5.2.4 on 2026-09-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_container_gross_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="containertype",
            name="abbreviation",
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
