# Generated by Django 5.2.4 on 2026-09-21 02:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_purchaseorderitem_purchase_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleorder",
            name="arrival_port",
        ),
        migrations.RemoveField(
            model_name="saleorder",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="saleorder",
            name="shipment_port",
        ),
        migrations.RemoveField(
            model_name="saleorder",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="saleorder",
            name="provider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_orders",
                to="core.provider",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saleorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="user",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_orders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="saleorder",
            name="incoterms",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_orders",
                to="core.incoterms",
            ),
        ),
        migrations.AlterField(
            model_name="saleorder",
            name="processing_plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_orders",
                to="core.processingplant",
            ),
        ),
        migrations.AlterField(
            model_name="saleorder",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_orders",
                to="core.purchaseorder",
            ),
        ),
        migrations.CreateModel(
            name="SaleOrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "measurement_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.measurement_unit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_order_items",
                        to="core.productproviderpresentation",
                    ),
                ),
            ],
        ),
    ]
