# Generated by Django 5.2.4 on 2026-09-21 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_saleorder_arrival_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorderitems",
            name="sale_order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_order_items",
                to="core.saleorder",
            ),
            preserve_default=False,
        ),
    ]
