# Generated by Django 5.2.4 on 2026-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_containertype_abbreviation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bussines_name", models.CharField()),
                (
                    "business_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "business_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nit_code", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("contacts", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["bussines_name"],
                "permissions": [("manage_customers", "Can manage customers")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
