# Generated by Django 5.2.4 on 2026-09-21 21:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_saleorderitems_sale_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleorderitems",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Sale Order Item",
                "verbose_name_plural": "Sale Order Items",
            },
        ),
        migrations.CreateModel(
            name="ProviderInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pi_number", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "invoice_image",
                    models.ImageField(
                        blank=True,
                        default="invoices/invoice_image_default.png",
                        null=True,
                        upload_to="invoices/pics",
                    ),
                ),
                (
                    "provider_sale_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="core.saleorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Invoice",
                "verbose_name_plural": "Provider Invoices",
                "ordering": ["issue_date"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ProviderInvoicePayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                ("payment_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.providerinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Invoice Payment",
                "verbose_name_plural": "Provider Invoice Payments",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.AddIndex(
            model_name="providerinvoice",
            index=models.Index(
                fields=["pi_number"], name="core_provid_pi_numb_1d2911_idx"
            ),
        ),
    ]
