# Generated by Django 5.2.4 on 2026-09-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "default_permissions": [],
                "ordering": ["business_name"],
                "permissions": [("manage_customers", "Can manage customers")],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="bussines_name",
            new_name="business_name",
        ),
    ]
