# Generated by Django 5.2.4 on 2026-09-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="core.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saleorder",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_orders",
                to="core.customer",
            ),
            preserve_default=False,
        ),
    ]
