# Generated by Django 5.2.4 on 2025-10-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_cart_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
    ]
