# Generated by Django 5.2.4 on 2026-09-26 20:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_purchaseorder_customer_saleorder_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorderitems",
            name="unit_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
