# Generated by Django 5.2.4 on 2026-09-22 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_invoice_paymentagreement_shippingcompanyinvoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderInvoiceV2",
            fields=[
                (
                    "invoice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.invoice",
                    ),
                ),
                (
                    "sale_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="core.saleorder",
                    ),
                ),
            ],
            bases=("core.invoice",),
        ),
    ]
