# Generated by Django 5.2.4 on 2025-10-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_order_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactaddress",
            name="reference",
            field=models.TextField(blank=True, null=True),
        ),
    ]
