# Generated by Django 5.2.4 on 2026-09-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_providerinvoicev2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "default_permissions": [],
                "permissions": [
                    ("manage_purchase_orders", "Can manage purchase orders")
                ],
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="saleorder",
            options={
                "default_permissions": [],
                "ordering": ["-so_date"],
                "permissions": [("manage_sale_orders", "Can manage sale orders")],
                "verbose_name": "Sale Order",
                "verbose_name_plural": "Sale Orders",
            },
        ),
    ]
