# Generated by Django 5.2.4 on 2026-09-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_saleorderitems_unit_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
            ),
        ),
    ]
