# Generated by Django 5.2.4 on 2026-09-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_purchaseorder_options_alter_saleorder_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="invoicepayment",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Invoice Payment",
                "verbose_name_plural": "Invoice Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentagreement",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Payment Agreement",
                "verbose_name_plural": "Payment Agreement",
            },
        ),
        migrations.AlterModelOptions(
            name="productproviderpresentation",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_purchase_orders", "Can manage purchase orders")
                ],
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorderitem",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Purchase Order Item",
                "verbose_name_plural": "Purchase Order Items",
            },
        ),
    ]
