# Generated by Django 5.2.4 on 2025-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_contactaddress_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatus",
            name="delivery_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderstatus",
            name="store_status",
            field=models.BooleanField(default=False),
        ),
    ]
