# Generated by Django 5.2.4 on 2026-09-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Completed"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                ],
                default="pending",
            ),
        ),
    ]
