# Generated by Django 5.2.4 on 2026-09-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cancelation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
