# Generated by Django 5.2.4 on 2025-10-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_orderstatus_delivery_status_orderstatus_store_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_order", "Can manage order"),
                    ("change_order_status", "Can change order status"),
                ],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
