# Generated by Django 5.2.4 on 2026-09-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_invoice_options_alter_invoicepayment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerinvoice",
            name="invoice_image",
        ),
    ]
