# Generated by Django 5.2.4 on 2026-09-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_invoice_cancelation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="last_free_day",
            field=models.DateField(blank=True, null=True),
        ),
    ]
