# Generated by Django 5.2.4 on 2025-10-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatus",
            name="code_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
