# Generated by Django 5.2.4 on 2026-09-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_providerinvoice_invoice_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentagreement",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "permissions": [
                    ("manage_payment_agreements", "Can manage payment agreements")
                ],
                "verbose_name": "Payment Agreement",
                "verbose_name_plural": "Payment Agreement",
            },
        ),
    ]
