# Generated by Django 5.2.4 on 2025-10-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_orderstatus_code_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="waha_api_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="waha_api_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="waha_api_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
