# Generated by Django 5.2.4 on 2026-09-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_container_last_free_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="last_free_day",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Completed"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
