# Generated by Django 5.2.4 on 2026-09-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_paymentagreement_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingcompanyinvoice",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Shipping Company Invoice",
                "verbose_name_plural": "Shipping Company Invoices",
            },
        ),
    ]
