# Generated by Django 5.2.4 on 2025-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_config_waha_api_password_config_waha_api_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="enzona_api_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="enzona_consumer_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="enzona_consumer_secret",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
