# Generated by Django 5.2.4 on 2025-10-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_config_enzona_api_url_config_enzona_consumer_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HairTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Hair Type",
                "verbose_name_plural": "Hair Types",
                "ordering": ["id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="hair_types",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="core.hairtypes"
            ),
        ),
    ]
