# Generated by Django 5.2.4 on 2025-10-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_hairtypes_product_hair_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="hair_types",
            field=models.ManyToManyField(related_name="products", to="core.hairtypes"),
        ),
    ]
