# Generated by Django 5.2.4 on 2025-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_product_hair_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="specifications",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
