# Generated by Django 5.2.4 on 2025-10-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_specifications_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specificationdetails",
            old_name="description",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="product",
            name="specifications",
        ),
        migrations.RemoveField(
            model_name="specificationdetails",
            name="color",
        ),
        migrations.RemoveField(
            model_name="specificationdetails",
            name="name",
        ),
        migrations.RemoveField(
            model_name="specificationdetails",
            name="specification_image",
        ),
        migrations.AddField(
            model_name="specificationdetails",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specification_details",
                to="core.product",
            ),
            preserve_default=False,
        ),
    ]
