# Generated by Django 5.2.4 on 2025-10-20 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_rename_description_specificationdetails_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specificationdetails",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications_details",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="specificationdetails",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications_details",
                to="core.specifications",
            ),
        ),
    ]
