# Generated by Django 5.2.4 on 2025-11-01 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0017_alter_blockfilterpost_limit_and_more"),
        ("core", "0029_alter_specificationdetails_product_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["client", "product"], name="core_cart_client__17074d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactaddress",
            index=models.Index(fields=["user"], name="core_contac_user_id_75d3d2_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationuser",
            index=models.Index(fields=["user"], name="core_notifi_user_id_b22395_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["client", "-creation_date"],
                name="core_order_client__1f71ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderproducts",
            index=models.Index(
                fields=["order", "product"], name="core_orderp_order_i_cfb313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatus",
            index=models.Index(
                fields=["code_name"], name="core_orders_code_na_f4027b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordertracking",
            index=models.Index(
                fields=["order", "status"], name="core_ordert_order_i_e10c03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "active"], name="core_produc_categor_0a9d66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "active"], name="core_produc_brand_i_5a64b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["provider", "active"], name="core_produc_provide_91235b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product"], name="core_review_product_99ff2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "rating"], name="core_review_product_3ee2f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "rating", "-review_date"],
                name="core_review_product_9e5526_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="specificationdetails",
            index=models.Index(
                fields=["product"], name="core_specif_product_f34eef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specificationdetails",
            index=models.Index(
                fields=["product", "specification"],
                name="core_specif_product_0d7bb4_idx",
            ),
        ),
    ]
