# Generated by Django 5.2.4 on 2025-11-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_cart_core_cart_client__17074d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
