# Generated by Django 5.2.4 on 2025-11-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_currency_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="specifications",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
