# Generated by Django 5.2.4 on 2025-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_specifications_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="minimal_stock",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
