# Generated by Django 5.2.4 on 2025-11-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_product_minimal_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="hairtypes",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
