# Generated by Django 5.2.4 on 2025-11-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_hairtypes_active_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="transfermovil_api_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="transfermovil_callback_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="transfermovil_seed",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="transfermovil_source",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="transfermovil_username",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
