# Generated by Django 5.2.4 on 2025-11-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_config_transfermovil_api_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="business_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="business_email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="business_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="business_schedule",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="billing_email",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="confirm_register_url",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="config",
            name="front_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="config",
            name="login_url",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="config",
            name="transfermovil_api_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="transfermovil_callback_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="transfermovil_seed",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="transfermovil_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="transfermovil_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="waha_api_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
