# Generated by Django 5.2.4 on 2025-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_config_business_address_config_business_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="confirm_register_url",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="config",
            name="enzona_api_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="enzona_consumer_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="enzona_consumer_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="front_url",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="config",
            name="login_url",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="config",
            name="recover_password_url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
