# Generated by Django 5.2.4 on 2025-12-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_config_confirm_register_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="backend_url",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="config",
            name="tropipay_api_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="tropipay_client_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="tropipay_client_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="tropipay_paymentcards_account_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
