# Generated by Django 5.2.4 on 2025-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_config_backend_url_config_tropipay_api_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="logo_horizontal_dark",
            field=models.ImageField(
                default="config/config_image_default.png", upload_to="config/pics"
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="logo_horizontal_light",
            field=models.ImageField(
                default="config/config_image_default.png", upload_to="config/pics"
            ),
        ),
    ]
