# Generated by Django 5.2.4 on 2025-12-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_config_logo_horizontal_dark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="brand",
                to="core.brand",
            ),
        ),
    ]
