# Generated by Django 5.2.4 on 2026-01-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_order_seller_alter_order_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproducts",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
