# Generated by Django 5.2.4 on 2026-01-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_orderproducts_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="ceated_at",
            new_name="created_at",
        ),
    ]
