# Generated by Django 5.2.4 on 2026-01-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_rename_ceated_at_product_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproducts",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
    ]
