# Generated by Django 5.2.4 on 2026-01-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_orderproducts_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="hair_types",
        ),
        migrations.DeleteModel(
            name="HairTypes",
        ),
    ]
