# Generated by Django 5.2.4 on 2026-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_product_hair_types_delete_hairtypes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "percentual_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fixed_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_days", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Credit Type",
                "verbose_name_plural": "Credit Types",
                "ordering": ["-id"],
                "permissions": [("manage_credittypes", "Can manage credit types")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
