# Generated by Django 5.2.4 on 2026-01-13 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_credittype"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="credit_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_credit",
                to="core.credittype",
            ),
        ),
    ]
