# Generated by Django 5.2.4 on 2026-01-14 13:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_order_credit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
