# Generated by Django 5.2.4 on 2026-01-20 22:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_order_amount_order_credit_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("part_code", models.CharField(max_length=100)),
                (
                    "quantity_per_box",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "cost_price_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "cost_price_cup",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "sale_price_cup",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory entry",
                "verbose_name_plural": "Inventory entries",
                "ordering": ["-id"],
                "permissions": [
                    ("manage_inventory_entry", "Can manage inventory entry")
                ],
            },
        ),
    ]
