# Generated by Django 5.2.4 on 2026-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_inventoryentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventoryentry",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="inventoryentry",
            name="entry_sheet_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryentry",
            name="imported",
            field=models.BooleanField(default=False),
        ),
    ]
