# Generated by Django 5.2.4 on 2026-01-28 19:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_product_cost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproducts",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
