# Generated by Django 5.2.4 on 2026-02-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_orderproducts_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventoryentry",
            old_name="imported",
            new_name="updated",
        ),
    ]
