# Generated by Django 5.2.4 on 2026-02-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_rename_imported_inventoryentry_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryentry",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_inventory_entry", "Can manage inventory entry")
                ],
                "verbose_name": "Inventory entry",
                "verbose_name_plural": "Inventory entries",
            },
        ),
    ]
