# Generated by Django 5.2.4 on 2026-02-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_inventoryentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="business_account",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="business_licence",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="business_nit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
