# Generated by Django 5.2.4 on 2026-02-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_config_business_account_config_business_licence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_wholesale_price",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_minimum",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
