# Generated by Django 5.2.4 on 2026-02-14 16:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_product_has_wholesale_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="wholesale_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
