# Generated by Django 5.2.4 on 2026-02-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_product_wholesale_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specifications",
            options={
                "default_permissions": [],
                "ordering": ["id"],
                "permissions": [("manage_specifications", "Can manage specifications")],
                "verbose_name": "Specification",
                "verbose_name_plural": "Specifications",
            },
        ),
    ]
