# Generated by Django 5.2.4 on 2026-02-28 14:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_alter_specifications_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_identificator", models.CharField(max_length=255, unique=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory entry",
                "verbose_name_plural": "Inventory entries",
                "ordering": ["-id"],
                "permissions": [
                    ("manage_inventory_entry", "Can manage inventory entry")
                ],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.DeleteModel(
            name="InventoryEntry",
        ),
    ]
