# Generated by Django 5.2.4 on 2026-02-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_batch_delete_inventoryentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [("manage_batch_entry", "Can manage batch entry")],
                "verbose_name": "Batch entry",
                "verbose_name_plural": "Batch entries",
            },
        ),
    ]
