# Generated by Django 5.2.4 on 2026-02-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_batch_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
