# Generated by Django 5.2.4 on 2026-02-28 15:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_alter_batch_created_at_alter_batch_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=1024)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "quantity_sold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                ("sold", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Item",
                "verbose_name_plural": "Batch Items",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
