# Generated by Django 5.2.4 on 2026-02-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_batchitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batch_items",
                to="core.product",
            ),
        ),
    ]
