# Generated by Django 5.2.4 on 2026-02-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0030_alter_blockfilterbrand_options_and_more"),
        ("core", "0064_batchitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="part_code",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["part_code", "active"], name="core_produc_part_co_4d7c25_idx"
            ),
        ),
    ]
