# Generated by Django 5.2.4 on 2026-03-07 17:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_product_part_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "batch_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_product",
                        to="core.batchitem",
                    ),
                ),
                (
                    "order_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_item",
                        to="core.orderproducts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Batch",
                "verbose_name_plural": "Product Batch",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
