# Generated by Django 5.2.4 on 2026-05-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_productbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="admin_logo_horizontal_dark",
            field=models.ImageField(
                default="config/config_image_default.png", upload_to="config/pics"
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="admin_logo_horizontal_light",
            field=models.ImageField(
                default="config/config_image_default.png", upload_to="config/pics"
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="waha_api_session",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
