# Generated by Django 5.2.4 on 2026-06-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_config_admin_logo_horizontal_dark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="waha_api_apikey",
            field=models.CharField(
                blank=True, default="admin", max_length=255, null=True
            ),
        ),
    ]
