# Generated by Django 5.2.4 on 2026-06-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_config_waha_api_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatus",
            name="merge_status",
            field=models.BooleanField(default=False),
        ),
    ]
