# Generated by Django 5.2.4 on 2026-06-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_vehicletype_vehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_images",
        ),
    ]
