# Generated by Django 5.2.4 on 2026-06-13 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0030_alter_blockfilterbrand_options_and_more"),
        ("core", "0071_remove_product_product_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImageOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cms.blockmedia"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_images_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="core.ProductImageOrder",
                to="cms.blockmedia",
            ),
        ),
        migrations.AddIndex(
            model_name="productimageorder",
            index=models.Index(
                fields=["product", "id"], name="core_produc_product_49f199_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productimageorder",
            unique_together={("product", "media")},
        ),
    ]
