# Generated by Django 5.2.4 on 2026-06-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_productimageorder_product_product_images_new_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_images_new",
            new_name="product_images",
        ),
    ]
