# Generated by Django 5.2.4 on 2026-06-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_rename_product_images_new_product_product_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimageorder",
            options={"default_permissions": [], "ordering": ["id"]},
        ),
    ]
