# Generated by Django 5.2.4 on 2026-06-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0030_alter_blockfilterbrand_options_and_more"),
        ("core", "0074_alter_productimageorder_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimageorder",
            old_name="media",
            new_name="blockmedia",
        ),
        migrations.AlterUniqueTogether(
            name="productimageorder",
            unique_together={("product", "blockmedia")},
        ),
    ]
