# Generated by Django 5.2.4 on 2026-06-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_rename_media_productimageorder_blockmedia_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="composite",
            new_name="use_custom_template",
        ),
    ]
