# Generated by Django 5.2.4 on 2026-06-15 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_alter_vehicle_driver"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("lon", models.DecimalField(decimal_places=2, max_digits=10)),
                ("alt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cog", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vel", models.DecimalField(decimal_places=2, max_digits=10)),
                ("acc", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vac", models.DecimalField(decimal_places=2, max_digits=10)),
                ("batt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="core.vehicle",
                    ),
                ),
            ],
        ),
    ]
