# Generated by Django 5.2.4 on 2026-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_config_mqtt_client_id_config_mqtt_host_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="mqtt_port",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
