# Generated by Django 5.2.4 on 2026-06-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_alter_vehicle_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclelocation",
            name="vel",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
