# Generated by Django 5.2.4 on 2026-06-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_alter_vehiclelocation_vel"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclelocation",
            name="broker_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
