# Generated by Django 5.2.4 on 2026-06-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_vehiclelocation_broker_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclelocation",
            name="acc",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="alt",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="cog",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="lat",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="lon",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="vac",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
