# Generated by Django 5.2.4 on 2026-06-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_alter_vehiclelocation_acc_alter_vehiclelocation_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclelocation",
            name="acc",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="alt",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="cog",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="lat",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="lon",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="vac",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
