# Generated by Django 5.2.4 on 2026-06-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_alter_vehiclelocation_acc_alter_vehiclelocation_alt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehiclelocation",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "Vehicle Location",
                "verbose_name_plural": "Vehicle Locations",
            },
        ),
    ]
