# Generated by Django 5.2.4 on 2026-06-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_alter_vehiclelocation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="astrack_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="astrack_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
