# Generated by Django 5.2.4 on 2026-06-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_config_astrack_websocket_vehicle_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclelocation",
            name="batt",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
