# Generated by Django 5.2.4 on 2026-06-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_alter_vehiclelocation_batt"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="use_mobile_gps",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vehiclelocation",
            name="batt",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
