# Generated by Django 5.2.4 on 2026-07-22 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_vehicle_use_mobile_gps_alter_vehiclelocation_batt"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="odoo_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="odoo_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 7, 22, 3, 55, 42, 370399, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="odoo_order_id",
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="odoo_product_id",
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="code_sku",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="part_code",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
