# Generated by Django 5.2.4 on 2026-07-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_config_odoo_token_config_odoo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="order_expiration_days",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
