# Generated by Django 5.2.4 on 2026-07-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_config_order_expiration_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="exchange_rate",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="received_date",
        ),
        migrations.RemoveField(
            model_name="batchitem",
            name="name",
        ),
        migrations.RemoveField(
            model_name="batchitem",
            name="part_code",
        ),
    ]
