# Generated by Django 5.2.4 on 2026-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_remove_batch_exchange_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchitem",
            name="processed",
        ),
        migrations.AddField(
            model_name="batch",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
