# Generated by Django 5.2.4 on 2026-07-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_remove_batchitem_processed_batch_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="odoo_order_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
