# Generated by Django 5.2.4 on 2026-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_alter_order_odoo_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="productbatch",
            name="reserved",
            field=models.BooleanField(default=True),
        ),
    ]
