# Generated by Django 5.2.4 on 2026-07-29 21:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_remove_batch_total_amount_productbatch_reserved"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batchitem",
            name="amount_sold",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
