# Generated by Django 5.2.4 on 2026-08-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_batch_processed_at_batchitem_amount_sold"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={
                "default_permissions": [],
                "ordering": ["-processed_at", "-created_at"],
                "permissions": [("manage_batch_entry", "Can manage batch entry")],
                "verbose_name": "Batch entry",
                "verbose_name_plural": "Batch entries",
            },
        ),
    ]
