# Generated by Django 5.2.4 on 2026-09-08 14:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_purchaseorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incoterms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Incoterms",
                "verbose_name_plural": "Incoterms",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
                "indexes": [
                    models.Index(
                        fields=["abbreviation"], name="core_incote_abbrevi_82723b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Port",
                "verbose_name_plural": "Ports",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
                "indexes": [
                    models.Index(
                        fields=["abbreviation"], name="core_port_abbrevi_f76af2_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessingPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phytosanitary_permit", models.BooleanField(default=False)),
                (
                    "phytosanitary_permit_expires",
                    models.DateField(blank=True, null=True),
                ),
                ("veterinary_permit", models.BooleanField(default=False)),
                ("veterinary_permit_expires", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Processing Plant",
                "verbose_name_plural": "Processing Plants",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
                "indexes": [
                    models.Index(fields=["name"], name="core_proces_name_c5d026_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="SaleOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_number", models.CharField(max_length=100)),
                ("so_date", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "arrival_port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrival_sale_orders",
                        to="core.port",
                    ),
                ),
                (
                    "incoterms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_orders",
                        to="core.incoterms",
                    ),
                ),
                (
                    "processing_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_orders",
                        to="core.processingplant",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_orders",
                        to="core.purchaseorder",
                    ),
                ),
                (
                    "shipment_port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_sale_orders",
                        to="core.port",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Order",
                "verbose_name_plural": "Sale Orders",
                "ordering": ["-so_date"],
                "abstract": False,
                "default_permissions": [],
                "indexes": [
                    models.Index(
                        fields=["so_number"], name="core_saleor_so_numb_076461_idx"
                    )
                ],
            },
        ),
    ]
