# Generated by Django 5.2.4 on 2026-10-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("parent", "name")},
        ),
        migrations.AddField(
            model_name="folder",
            name="root",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RemoveField(
            model_name="folder",
            name="owner",
        ),
    ]
