# Generated by Django 5.2.4 on 2026-10-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0002_alter_folder_unique_together_folder_root_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("folder", "name")},
        ),
        migrations.RemoveField(
            model_name="file",
            name="owner",
        ),
    ]
