# Generated by Django 5.2.4 on 2026-10-04 16:35

import file_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0003_alter_file_unique_together_remove_file_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=file_manager.models.file_upload_path),
        ),
    ]
