# Generated by Django 5.2.4 on 2026-09-18 18:04

import cms.models
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockBUTTON",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Block BUTTON",
                "verbose_name_plural": "Blocks BUTTON",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockCARD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                ("reverse", models.BooleanField(default=False)),
                ("spotlight", models.BooleanField(default=False)),
                (
                    "spotlight_color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("highlight", models.BooleanField(default=False)),
                (
                    "highlight_color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("variant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Block CARD",
                "verbose_name_plural": "Blocks CARD",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockCARDGROUP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                (
                    "card_group_type",
                    models.CharField(
                        choices=[("GR", "Grid"), ("FX", "Flex")], max_length=5
                    ),
                ),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/10", "One tenth"),
                            ("1/9", "One ninth"),
                            ("1/8", "One eighth"),
                            ("1/7", "One seventh"),
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "One half"),
                            ("1", "Full width"),
                        ],
                        max_length=20,
                    ),
                ),
                ("justify", models.CharField(default="center", max_length=20)),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        default="vertical",
                        max_length=15,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, default="md", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Block CARD GROUP",
                "verbose_name_plural": "Blocks CARD GROUP",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockCAROUSEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/10", "One tenth"),
                            ("1/9", "One ninth"),
                            ("1/8", "One eighth"),
                            ("1/7", "One seventh"),
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "One half"),
                            ("1", "Full width"),
                        ],
                        max_length=20,
                    ),
                ),
                ("indicators", models.BooleanField(default=False)),
                ("autoplay", models.BooleanField(default=False)),
                (
                    "autoplay_props",
                    models.JSONField(default=cms.models.default_autoplay_props),
                ),
                ("autoscroll", models.BooleanField(default=False)),
                (
                    "autoscroll_props",
                    models.JSONField(default=cms.models.default_autoscroll_props),
                ),
                ("arrows", models.BooleanField(default=False)),
                (
                    "blocks_orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        default="vertical",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Block CAROUSEL",
                "verbose_name_plural": "Blocks CAROUSEL",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                ("size", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reverse", models.BooleanField(default=False)),
                ("variant", models.CharField(blank=True, max_length=25, null=True)),
                ("buttons", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "CTA block",
                "verbose_name_plural": "CTA blocks",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockFilterBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                ("filters", models.JSONField(blank=True, default=None, null=True)),
                ("exclude", models.JSONField(blank=True, default=None, null=True)),
                ("limit", models.PositiveIntegerField(default=10)),
                ("order_by", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "variant",
                    models.CharField(
                        blank=True, default="ghost", max_length=25, null=True
                    ),
                ),
                ("show_link", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Blog Filter Brand",
                "verbose_name_plural": "Blog Filter Brands",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockFilterPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                ("filters", models.JSONField(blank=True, default=None, null=True)),
                ("exclude", models.JSONField(blank=True, default=None, null=True)),
                ("limit", models.PositiveIntegerField(default=10)),
                ("order_by", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "verbose_name": "Blog Filter Post",
                "verbose_name_plural": "Blog Filter Post",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockFilterProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                ("filters", models.JSONField(blank=True, default=None, null=True)),
                ("exclude", models.JSONField(blank=True, default=None, null=True)),
                ("limit", models.PositiveIntegerField(default=10)),
                ("order_by", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "verbose_name": "Blog Filter Product",
                "verbose_name_plural": "Blog Filter Products",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockFOOTERLINKS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block FOOTER LINKS",
                "verbose_name_plural": "Blocks FOOTER LINKS",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockHTML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                ("styles", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Block HTML",
                "verbose_name_plural": "Blocks HTML",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockMarkdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
            ],
            options={
                "verbose_name": "Block Markdown",
                "verbose_name_plural": "Blocks Markdown",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockMarquee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reverse", models.BooleanField(default=False)),
                ("overlay", models.BooleanField(default=True)),
                ("pauseOnHover", models.BooleanField(default=True)),
                ("repeat", models.IntegerField(default=4)),
            ],
            options={
                "verbose_name": "Marquee block",
                "verbose_name_plural": "Marquee block",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockMEDIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_group",
                    models.CharField(
                        choices=[
                            ("products", "Productos"),
                            ("cms", "Contenido"),
                            ("blog", "Publicaciones"),
                        ],
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "media",
                    models.FileField(upload_to=cms.models.media_group_directory_path),
                ),
            ],
            options={
                "verbose_name": "Block MEDIA",
                "verbose_name_plural": "Blocks MEDIA",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockMEDIACARD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                (
                    "type",
                    models.CharField(
                        choices=[("simple", "Simple"), ("responsive", "Responsive")],
                        default="simple",
                        max_length=25,
                    ),
                ),
            ],
            options={
                "verbose_name": "Block MEDIA CARD",
                "verbose_name_plural": "Blocks MEDIA CARD",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockNAVBAR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Nav bar",
                "verbose_name_plural": "Nav bars",
                "ordering": ["-id"],
                "permissions": [("manage_blocknavbar", "Can manage nav bar")],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/10", "One tenth"),
                            ("1/9", "One ninth"),
                            ("1/8", "One eighth"),
                            ("1/7", "One seventh"),
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "One half"),
                            ("1", "Full width"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        default="vertical",
                        max_length=15,
                    ),
                ),
                ("wide", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Blog Page",
                "verbose_name_plural": "Blog Pages",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Page",
                "verbose_name_plural": "Landing Pages",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ShopPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/10", "One tenth"),
                            ("1/9", "One ninth"),
                            ("1/8", "One eighth"),
                            ("1/7", "One seventh"),
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "One half"),
                            ("1", "Full width"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        default="vertical",
                        max_length=15,
                    ),
                ),
                ("wide", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Shop Page",
                "verbose_name_plural": "Shop Pages",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockHERO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                ("name", models.CharField(default="Bloque HERO", max_length=255)),
                (
                    "hero_type",
                    models.CharField(
                        choices=[("IMG", "Image"), ("GAL", "Gallery")], max_length=5
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("Left", "Left"), ("Right", "Right")], max_length=10
                    ),
                ),
                (
                    "gallery",
                    models.ManyToManyField(related_name="hero", to="cms.blockmedia"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hero_blocks",
                        to="cms.blockmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "HERO block",
                "verbose_name_plural": "HERO blocks",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockCONTAINER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1024)),
                ("wide", models.BooleanField(default=True)),
                (
                    "back_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="container_blocks",
                        to="cms.blockmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block Container",
                "verbose_name_plural": "Blocks Container",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Blocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=1024)),
                ("color", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_types",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_id", models.IntegerField(default=0)),
                ("item_id", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                ("field_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_blocks",
                        to="cms.blocks",
                    ),
                ),
                (
                    "local_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_items",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composer",
                "verbose_name_plural": "Composers",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/10", "One tenth"),
                            ("1/9", "One ninth"),
                            ("1/8", "One eighth"),
                            ("1/7", "One seventh"),
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "One half"),
                            ("1", "Full width"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "back_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="footer",
                        to="cms.blockmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footers",
                "ordering": ["-id"],
                "permissions": [("manage_footer", "Can manage footer")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "in_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="header_in_menu",
                        to="cms.blocknavbar",
                    ),
                ),
                (
                    "out_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="header_out_menu",
                        to="cms.blocknavbar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header",
                "verbose_name_plural": "Headers",
                "ordering": ["-id"],
                "permissions": [("manage_header", "Can manage header")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="RelationShips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("L", "List"), ("C", "Creation"), ("A", "All")],
                        default="A",
                        max_length=5,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="cms.blocks",
                    ),
                ),
                (
                    "local_content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_ids",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "RelationShip",
                "verbose_name_plural": "RelationShips",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockBUTTONTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blockbutton",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block BUTTON Translation",
                "db_table": "cms_blockbutton_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blockbutton_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockCARDGROUPTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("subtitle", models.TextField(blank=True, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blockcardgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block CARD GROUP Translation",
                "db_table": "cms_blockcardgroup_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blockcardgroup_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockCTATranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blockcta",
                    ),
                ),
            ],
            options={
                "verbose_name": "CTA block Translation",
                "db_table": "cms_blockcta_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blockcta_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockFOOTERLINKSTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("links", models.JSONField(default=list)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blockfooterlinks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block FOOTER LINKS Translation",
                "db_table": "cms_blockfooterlinks_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blockfooterlinks_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockHTMLTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blockhtml",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block HTML Translation",
                "db_table": "cms_blockhtml_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blockhtml_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockMarkdownTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blockmarkdown",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block Markdown Translation",
                "db_table": "cms_blockmarkdown_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blockmarkdown_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockCARDTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blockcard",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="cms.blockmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block CARD Translation",
                "db_table": "cms_blockcard_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blockcard_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockMEDIACARDTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("url", models.CharField(max_length=1024)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_card_blocks",
                        to="cms.blockmedia",
                    ),
                ),
                (
                    "image_lg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_card_blocks_lg",
                        to="cms.blockmedia",
                    ),
                ),
                (
                    "image_md",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_card_blocks_md",
                        to="cms.blockmedia",
                    ),
                ),
                (
                    "image_sm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_card_blocks_sm",
                        to="cms.blockmedia",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blockmediacard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block MEDIA CARD Translation",
                "db_table": "cms_blockmediacard_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blockmediacard_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlockNAVBARTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("items", models.JSONField(default=list)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blocknavbar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nav bar Translation",
                "db_table": "cms_blocknavbar_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blocknavbar_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlogPageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.blogpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Page Translation",
                "db_table": "cms_blogpage_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_blogpage_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Translation",
                "db_table": "cms_page_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_page_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ShopPageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.shoppage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Page Translation",
                "db_table": "cms_shoppage_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="cms_shoppage_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
