# Generated by Django 5.2.4 on 2025-09-16 14:39

import cms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockBUTTON",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Block BUTTON",
                "verbose_name_plural": "Blocks BUTTON",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockCARDGROUP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("label", models.CharField(blank=True, max_length=1024, null=True)),
                ("subtitle", models.TextField(blank=True, null=True)),
                (
                    "card_group_type",
                    models.CharField(
                        choices=[("GR", "Grid"), ("FX", "Flex")], max_length=5
                    ),
                ),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "In Half"),
                            ("1", "Wide"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Block CARD GROUP",
                "verbose_name_plural": "Blocks CARD GROUP",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockFOOTERLINKS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("links", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Block FOOTER LINKS",
                "verbose_name_plural": "Blocks FOOTER LINKS",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockHTML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Bloque HTML", max_length=255)),
                ("label", models.CharField(blank=True, max_length=1024, null=True)),
                ("content", models.CharField(max_length=1024)),
            ],
            options={
                "verbose_name": "Block HTML",
                "verbose_name_plural": "Blocks HTML",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockMEDIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_group",
                    models.CharField(
                        choices=[("products", "Productos"), ("cms", "Contenido")],
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "media",
                    models.FileField(upload_to=cms.models.media_group_directory_path),
                ),
            ],
            options={
                "verbose_name": "Block MEDIA",
                "verbose_name_plural": "Blocks MEDIA",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockNAVBAR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("items", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Nav bar",
                "verbose_name_plural": "Nav bars",
                "ordering": ["-id"],
                "permissions": [("manage_blocknavbar", "Can manage nav bar")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Page",
                "verbose_name_plural": "Landing Pages",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="ShopPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "In Half"),
                            ("1", "Wide"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Page",
                "verbose_name_plural": "Shop Pages",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockHERO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Bloque HERO", max_length=255)),
                (
                    "hero_type",
                    models.CharField(
                        choices=[("IMG", "Image"), ("GAL", "Gallery")], max_length=5
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("Left", "Left"), ("Right", "Right")], max_length=10
                    ),
                ),
                (
                    "gallery",
                    models.ManyToManyField(related_name="hero", to="cms.blockmedia"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hero_blocks",
                        to="cms.blockmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "HERO block",
                "verbose_name_plural": "HERO blocks",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockCONTAINER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=1024, null=True)),
                ("wide", models.BooleanField(default=True)),
                (
                    "back_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="container_blocks",
                        to="cms.blockmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block Container",
                "verbose_name_plural": "Blocks Container",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockCAROUSEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "In Half"),
                            ("1", "Wide"),
                        ],
                        max_length=20,
                    ),
                ),
                ("indicators", models.BooleanField(default=False)),
                ("autoplay", models.BooleanField(default=False)),
                ("arrows", models.BooleanField(default=False)),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="carousel", to="cms.blockmedia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Block CAROUSEL",
                "verbose_name_plural": "Blocks CAROUSEL",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockCARD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=1024, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("footer", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="cms.blockmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block CARD",
                "verbose_name_plural": "Blocks CARD",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BlockMEDIACARD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=1024, null=True)),
                ("url", models.CharField(max_length=1024)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_card_blocks",
                        to="cms.blockmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block MEDIA CARD",
                "verbose_name_plural": "Blocks MEDIA CARD",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Blocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=1024)),
                ("color", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_types",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_id", models.IntegerField(default=0)),
                ("item_id", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                ("field_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_blocks",
                        to="cms.blocks",
                    ),
                ),
                (
                    "local_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_items",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composer",
                "verbose_name_plural": "Composers",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "In Half"),
                            ("1", "Wide"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "back_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="footer",
                        to="cms.blockmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footers",
                "ordering": ["-id"],
                "permissions": [("manage_footer", "Can manage footer")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "in_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="header_in_menu",
                        to="cms.blocknavbar",
                    ),
                ),
                (
                    "out_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="header_out_menu",
                        to="cms.blocknavbar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header",
                "verbose_name_plural": "Headers",
                "ordering": ["-id"],
                "permissions": [("manage_header", "Can manage header")],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="RelationShips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("L", "List"), ("C", "Creation"), ("A", "All")],
                        default="A",
                        max_length=5,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="cms.blocks",
                    ),
                ),
                (
                    "local_content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_ids",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "RelationShip",
                "verbose_name_plural": "RelationShips",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
