# Generated by Django 5.2.4 on 2025-09-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockmedia",
            name="media_group",
            field=models.CharField(
                choices=[
                    ("products", "Productos"),
                    ("cms", "Contenido"),
                    ("blog", "Publicaciones"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]
