# Generated by Django 5.2.4 on 2025-10-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_alter_blockmedia_media_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("1/6", "One sixth"),
                            ("1/5", "One fifth"),
                            ("1/4", "One fourth"),
                            ("1/3", "One third"),
                            ("1/2", "In Half"),
                            ("1", "Wide"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Page",
                "verbose_name_plural": "Blog Pages",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
