# Generated by Django 5.2.4 on 2025-10-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_blogpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="orientation",
            field=models.CharField(
                choices=[("horizontal", "Horizontal"), ("vertical", "Vertical")],
                default="vertical",
                max_length=10,
            ),
        ),
    ]
