# Generated by Django 5.2.4 on 2025-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_blogpage_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockcardgroup",
            name="orientation",
            field=models.CharField(
                choices=[("horizontal", "Horizontal"), ("vertical", "Vertical")],
                default="vertical",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="orientation",
            field=models.CharField(
                choices=[("horizontal", "Horizontal"), ("vertical", "Vertical")],
                default="vertical",
                max_length=15,
            ),
        ),
    ]
