# Generated by Django 5.2.4 on 2025-10-06 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_blockcardgroup_orientation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockcard",
            name="footer",
        ),
        migrations.AddField(
            model_name="blockcard",
            name="highlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blockcard",
            name="highlight_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="blockcard",
            name="reverse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blockcard",
            name="spotlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blockcard",
            name="spotlight_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="blockcard",
            name="variant",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blockcard",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="cms.blockmedia",
            ),
        ),
    ]
