# Generated by Django 5.2.4 on 2025-10-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_remove_blockcard_footer_blockcard_highlight_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("head_line", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reverse", models.BooleanField(default=False)),
                ("variation", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "verbose_name": "CTA block",
                "verbose_name_plural": "CTA blocks",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
