# Generated by Django 5.2.4 on 2025-10-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_blockcta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockcta",
            name="head_line",
        ),
        migrations.RemoveField(
            model_name="blockcta",
            name="variation",
        ),
        migrations.AddField(
            model_name="blockcta",
            name="buttons",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="blockcta",
            name="variant",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
