# Generated by Django 5.2.4 on 2025-10-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_remove_blockcta_head_line_remove_blockcta_variation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockcarousel",
            name="images",
        ),
    ]
