# Generated by Django 5.2.4 on 2025-10-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_shoppage_orientation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockMarquee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reverse", models.BooleanField(default=False)),
                ("overlay", models.BooleanField(default=True)),
                ("pauseOnHover", models.BooleanField(default=True)),
                ("repeat", models.IntegerField(default=4)),
            ],
            options={
                "verbose_name": "Marquee block",
                "verbose_name_plural": "Marquee block",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.AddField(
            model_name="blockcta",
            name="label",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
