# Generated by Django 5.2.4 on 2025-10-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_blockmarquee_blockcta_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockcarousel",
            name="label",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="blockhero",
            name="label",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
