# Generated by Django 5.2.4 on 2025-10-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0012_blockcarousel_label_blockhero_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockcarousel",
            name="autoplay_props",
            field=models.JSONField(default={"delay": 3000}),
        ),
        migrations.AddField(
            model_name="blockcarousel",
            name="autoscroll",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blockcarousel",
            name="autoscroll_props",
            field=models.JSONField(default={"speed": 2}),
        ),
        migrations.AddField(
            model_name="blockcarousel",
            name="blocks_orientation",
            field=models.CharField(
                choices=[("horizontal", "Horizontal"), ("vertical", "Vertical")],
                default="vertical",
                max_length=15,
            ),
        ),
    ]
