# Generated by Django 5.2.4 on 2025-10-24 14:59

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0013_blockcarousel_autoplay_props_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockcarousel",
            name="autoplay_props",
            field=models.JSONField(default=cms.models.default_autoplay_props),
        ),
        migrations.AlterField(
            model_name="blockcarousel",
            name="autoscroll_props",
            field=models.JSONField(default=cms.models.default_autoscroll_props),
        ),
    ]
