# Generated by Django 5.2.4 on 2025-10-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0014_alter_blockcarousel_autoplay_props_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockFilterPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=None, null=True)),
                ("exclude", models.JSONField(blank=True, default=None, null=True)),
                ("limit", models.PositiveIntegerField(default=0)),
                ("order_by", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlockFilterProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=None, null=True)),
                ("exclude", models.JSONField(blank=True, default=None, null=True)),
                ("limit", models.PositiveIntegerField(default=0)),
                ("order_by", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
