# Generated by Django 5.2.4 on 2025-10-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0015_blockfilterpost_blockfilterproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockfilterpost",
            name="label",
            field=models.CharField(blank=True, default="", max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="blockfilterproduct",
            name="label",
            field=models.CharField(blank=True, default="", max_length=1024, null=True),
        ),
    ]
