# Generated by Django 5.2.4 on 2025-10-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0016_blockfilterpost_label_blockfilterproduct_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockfilterpost",
            name="limit",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="blockfilterproduct",
            name="limit",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
