# Generated by Django 5.2.4 on 2025-11-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0017_alter_blockfilterpost_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockcta",
            name="size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
