# Generated by Django 5.2.4 on 2025-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0018_blockcta_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockcta",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
