# Generated by Django 5.2.4 on 2025-11-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0019_alter_blockcta_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockhtml",
            name="name",
        ),
        migrations.AddField(
            model_name="blockcardgroup",
            name="size",
            field=models.CharField(blank=True, default="md", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="blockhtml",
            name="styles",
            field=models.JSONField(default=dict),
        ),
    ]
