# Generated by Django 5.2.4 on 2025-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0020_remove_blockhtml_name_blockcardgroup_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockhtml",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
