# Generated by Django 5.2.4 on 2025-12-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0021_alter_blockhtml_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockFilterBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=1024, null=True
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=None, null=True)),
                ("exclude", models.JSONField(blank=True, default=None, null=True)),
                ("limit", models.PositiveIntegerField(default=10)),
                ("order_by", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
