# Generated by Django 5.2.4 on 2025-12-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_blockfilterbrand"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockmediacard",
            name="image_lg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_card_blocks_lg",
                to="cms.blockmedia",
            ),
        ),
        migrations.AddField(
            model_name="blockmediacard",
            name="image_md",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_card_blocks_md",
                to="cms.blockmedia",
            ),
        ),
        migrations.AddField(
            model_name="blockmediacard",
            name="image_sm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_card_blocks_sm",
                to="cms.blockmedia",
            ),
        ),
        migrations.AddField(
            model_name="blockmediacard",
            name="type",
            field=models.CharField(
                choices=[("simple", "Simple"), ("responsive", "Responsive")],
                default="simple",
                max_length=25,
            ),
        ),
    ]
