# Generated by Django 5.2.4 on 2025-12-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0023_blockmediacard_image_lg_blockmediacard_image_md_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockcardgroup",
            name="design",
            field=models.CharField(
                choices=[
                    ("1/10", "One tenth"),
                    ("1/9", "One ninth"),
                    ("1/8", "One eighth"),
                    ("1/7", "One seventh"),
                    ("1/6", "One sixth"),
                    ("1/5", "One fifth"),
                    ("1/4", "One fourth"),
                    ("1/3", "One third"),
                    ("1/2", "One half"),
                    ("1", "Full width"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blockcarousel",
            name="design",
            field=models.CharField(
                choices=[
                    ("1/10", "One tenth"),
                    ("1/9", "One ninth"),
                    ("1/8", "One eighth"),
                    ("1/7", "One seventh"),
                    ("1/6", "One sixth"),
                    ("1/5", "One fifth"),
                    ("1/4", "One fourth"),
                    ("1/3", "One third"),
                    ("1/2", "One half"),
                    ("1", "Full width"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="design",
            field=models.CharField(
                choices=[
                    ("1/10", "One tenth"),
                    ("1/9", "One ninth"),
                    ("1/8", "One eighth"),
                    ("1/7", "One seventh"),
                    ("1/6", "One sixth"),
                    ("1/5", "One fifth"),
                    ("1/4", "One fourth"),
                    ("1/3", "One third"),
                    ("1/2", "One half"),
                    ("1", "Full width"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="design",
            field=models.CharField(
                choices=[
                    ("1/10", "One tenth"),
                    ("1/9", "One ninth"),
                    ("1/8", "One eighth"),
                    ("1/7", "One seventh"),
                    ("1/6", "One sixth"),
                    ("1/5", "One fifth"),
                    ("1/4", "One fourth"),
                    ("1/3", "One third"),
                    ("1/2", "One half"),
                    ("1", "Full width"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shoppage",
            name="design",
            field=models.CharField(
                choices=[
                    ("1/10", "One tenth"),
                    ("1/9", "One ninth"),
                    ("1/8", "One eighth"),
                    ("1/7", "One seventh"),
                    ("1/6", "One sixth"),
                    ("1/5", "One fifth"),
                    ("1/4", "One fourth"),
                    ("1/3", "One third"),
                    ("1/2", "One half"),
                    ("1", "Full width"),
                ],
                max_length=5,
            ),
        ),
    ]
