# Generated by Django 5.2.4 on 2025-12-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0024_alter_blockcardgroup_design_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockfilterbrand",
            name="variant",
            field=models.CharField(
                blank=True, default="ghost", max_length=25, null=True
            ),
        ),
    ]
