# Generated by Django 5.2.4 on 2025-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0025_blockfilterbrand_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockfilterbrand",
            name="show_link",
            field=models.BooleanField(default=True),
        ),
    ]
