# Generated by Django 5.2.4 on 2025-12-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0026_blockfilterbrand_show_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockcardgroup",
            name="justify",
            field=models.CharField(default="center", max_length=20),
        ),
    ]
