# Generated by Django 5.2.4 on 2025-12-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0027_blockcardgroup_justify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockcta",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
