# Generated by Django 5.2.4 on 2026-02-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0028_alter_blockcta_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockfilterbrand",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="blockfilterpost",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="blockfilterproduct",
            options={"default_permissions": []},
        ),
    ]
