# Generated by Django 5.2.4 on 2026-02-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0029_alter_blockfilterbrand_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockfilterbrand",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Blog Filter Brand",
                "verbose_name_plural": "Blog Filter Brands",
            },
        ),
        migrations.AlterModelOptions(
            name="blockfilterpost",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Blog Filter Post",
                "verbose_name_plural": "Blog Filter Post",
            },
        ),
        migrations.AlterModelOptions(
            name="blockfilterproduct",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "verbose_name": "Blog Filter Product",
                "verbose_name_plural": "Blog Filter Products",
            },
        ),
    ]
