# Generated by Django 5.2.4 on 2026-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0030_alter_blockfilterbrand_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockMarkdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=1024, null=True)),
                ("content", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Block Markdown",
                "verbose_name_plural": "Blocks Markdown",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
