"""
Django settings for logistic_backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.conf.global_settings import STATIC_ROOT
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    SECRET_KEY=(
        str,
        "django-insecure-girqzk)kz+m4#%odlryy91dky7+ys87)s2p5_p=dwm$rbq*b1_",
    ),
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ["*"]
CORS_ORIGIN_ALLOW_ALL = True
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

AUTH_USER_MODEL = "user.User"

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django_q",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "drf_spectacular",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "corsheaders",
    "cms.apps.CmsConfig",
    "core.apps.CoreConfig",
    "dashboard.apps.DashboardConfig",
    "blog.apps.BlogConfig",
    "delivery.apps.DeliveryConfig",
    "payments.apps.PaymentsConfig",
    "pos.apps.PosConfig",
    "promotions.apps.PromotionsConfig",
    "user.apps.UserConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "user.middlewares.EventLogMiddleware",
    "data_fetcher.middleware.GlobalRequestMiddleware",
]

ROOT_URLCONF = "logistic_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "logistic_backend.wsgi.application"
ASGI_APPLICATION = "logistic_backend.asgi.application"

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": (
        {
            "ENGINE": "django.db.backends.mysql",
            "HOST": env("DATABASE_HOST"),
            "PORT": env("DATABASE_PORT"),
            "NAME": env("DATABASE_NAME"),
            "USER": env("DATABASE_USER"),
            "PASSWORD": env("DATABASE_PASSWORD"),
            "ATOMIC_REQUEST": True,
            "POOL_OPTIONS": {
                "POOL_SIZE": 10,  # Número máximo de conexiones en el pool
                "MAX_OVERFLOW": 20,  # Máximo número de conexiones que pueden ser creadas beyond POOL_SIZE
                "RECYCLE": 1800,  # Tiempo en segundos después del cual una conexión es reciclada
                "PRE_PING": True,  # Verificar si la conexión está activa antes de usarla
                "ECHO": False,  # Mostrar logs de SQL (útil para debugging)
                "TIMEOUT": 30,  # Tiempo máximo de espera para obtener una conexión
            },
        }
        if env("DATABASE_HOST", default=None)
        else {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "ATOMIC_REQUEST": True,
        }
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "COERCE_DECIMAL_TO_STRING": False,
    "UPLOADED_FILES_USE_URL": True,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # "DATETIME_FORMAT": "%Y-%m-%d %H:%M",
    # "TIME_FORMAT": "%H:%M",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 50,
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

Q_CLUSTER = {
    "label": "Pending tasks",
    "name": "default",
    "workers": 3,
    "timeout": 50 * 60,
    "recycle": 50,
    "retry": 60 * 60,
    "queue_limit": 50,
    "bulk": 10,
    "max_attempts": 3,
    "orm": "default",
    # "ALT_CLUSTERS": {
    #     "high_priority": {
    #         "workers": 5,
    #         'max_attempts': 3
    #     },
    #     "whatsapp": {
    #         "workers": 5,
    #         'max_attempts': 1
    #     },
    # },
}
SPECTACULAR_SETTINGS = {
    "TITLE": "FEROS LOGISTIC API",
    "FILTER": True,
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,
    "SCHEMA_PATH_PREFIX": r".*/admin/.*",
    "SWAGGER_SETTINGS": {"filter": True},
    "ENUM_NAME_OVERRIDES": {
        "BlocksOrientationEnum": "cms.models.ORIENTATION_CHOICES",
    },
}

APPLICATION_DATA_PATH = os.path.join(BASE_DIR, "data/")

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en"
LANGUAGES = [
    ("es", _("Spanish")),
    ("en", _("English")),
]
LOCALE_PATHS = [os.path.join(BASE_DIR, "locale/")]

TIME_ZONE = "America/Havana"

USE_I18N = True

USE_TZ = True

TIME_INPUT_FORMATS = ("%H:%M",)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
MEDIA_URL = "/media/"
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = env("EMAIL_USE_TLS", bool, default=False)
EMAIL_USE_SSL = env("EMAIL_USE_SSL", bool, default=False)
EMAIL_HOST = env("EMAIL_HOST", str)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", str)
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", str)
EMAIL_PORT = env("EMAIL_PORT", int)
DEFAULT_FROM_EMAIL = f"FEROS GRUPO S.U.R.L. <{EMAIL_HOST_USER}>"
EMAIL_TIMEOUT = 30

SILENCED_SYSTEM_CHECKS = ["auth.E003"]
