from django.contrib import admin
from core.models import (
    Currency,
    Product,
    CompositeProduct,
    Category,
    Measurement_Unit,
    Provider,
    Country,
    Notification,
    NotificationType,
    NotificationUser,
    Specifications,
    SpecificationDetails,
    Order,
    OrderStatus,
    Brand,
    Review,
    Province,
    Municipality,
    ContactAddress,
    OrderProducts,
    OrderTracking,
    Cart,
    Config,
    Batch,
    BatchItem,
    ProductBatch,
    VehicleType,
    Vehicle,
)

admin.site.register(Currency)
admin.site.register(Product)
admin.site.register(CompositeProduct)
admin.site.register(Category)
admin.site.register(Measurement_Unit)
admin.site.register(Provider)
admin.site.register(Country)
admin.site.register(Notification)
admin.site.register(NotificationType)
admin.site.register(NotificationUser)
admin.site.register(Specifications)
admin.site.register(SpecificationDetails)
admin.site.register(Order)
admin.site.register(OrderStatus)
admin.site.register(Brand)
admin.site.register(Review)
admin.site.register(Province)
admin.site.register(Municipality)
admin.site.register(ContactAddress)
admin.site.register(OrderProducts)
admin.site.register(OrderTracking)
admin.site.register(Cart)
admin.site.register(Config)
admin.site.register(Batch)
admin.site.register(BatchItem)
admin.site.register(ProductBatch)
admin.site.register(VehicleType)
admin.site.register(Vehicle)
