from django.contrib import admin
from core.models import (
    Currency,
    Product,
    Category,
    Measurement_Unit,
    Provider,
    Country,
    Notification,
    NotificationType,
    NotificationUser,
    Specifications,
    SpecificationDetails,
    Brand,
    Presentation,
    ProductProvider,
    Config,
    PurchaseOrder,
    SaleOrder,
    SaleOrderItems,
    Port,
    ProcessingPlant,
    Incoterms,
    PaymentAgreement,
    ShippingCompanyInvoice,
    ShippingCompany,
    PurchaseOrderItem,
    ProductProviderPresentation,
    Invoice,
    InvoicePayment,
    Vessel,
    Booking,
    ContainerType,
    Container,
    ProviderInvoice,
)

admin.site.register(Currency)
admin.site.register(Product)
admin.site.register(Category)
admin.site.register(Measurement_Unit)
admin.site.register(Provider)
admin.site.register(Country)
admin.site.register(Notification)
admin.site.register(NotificationType)
admin.site.register(NotificationUser)
admin.site.register(Specifications)
admin.site.register(SpecificationDetails)
admin.site.register(Brand)
admin.site.register(Config)
admin.site.register(Presentation)
admin.site.register(ProductProvider)
admin.site.register(PurchaseOrder)
admin.site.register(PaymentAgreement)
admin.site.register(SaleOrder)
admin.site.register(Port)
admin.site.register(ProcessingPlant)
admin.site.register(Incoterms)
admin.site.register(SaleOrderItems)
admin.site.register(ShippingCompany)
admin.site.register(ShippingCompanyInvoice)
admin.site.register(ProviderInvoice)
admin.site.register(Vessel)
admin.site.register(PurchaseOrderItem)
admin.site.register(ProductProviderPresentation)
admin.site.register(Invoice)
admin.site.register(InvoicePayment)
admin.site.register(Booking)
admin.site.register(ContainerType)
admin.site.register(Container)
