from django.contrib import admin
from core.models import (
    Currency,
    Product,
    Category,
    Measurement_Unit,
    Provider,
    Country,
    Notification,
    NotificationType,
    NotificationUser,
    Specifications,
    SpecificationDetails,
    Brand,
    Presentation,
    ProductProvider,
    Config,
    PurchaseOrder,
    SaleOrder,
    SaleOrderItems,
    Port,
    ProcessingPlant,
    Incoterms,
    ProviderInvoice,
    ProviderInvoicePayments,
)

admin.site.register(Currency)
admin.site.register(Product)
admin.site.register(Category)
admin.site.register(Measurement_Unit)
admin.site.register(Provider)
admin.site.register(Country)
admin.site.register(Notification)
admin.site.register(NotificationType)
admin.site.register(NotificationUser)
admin.site.register(Specifications)
admin.site.register(SpecificationDetails)
admin.site.register(Brand)
admin.site.register(Config)
admin.site.register(Presentation)
admin.site.register(ProductProvider)
admin.site.register(PurchaseOrder)
admin.site.register(SaleOrder)
admin.site.register(Port)
admin.site.register(ProcessingPlant)
admin.site.register(Incoterms)
admin.site.register(SaleOrderItems)
admin.site.register(ProviderInvoice)
admin.site.register(ProviderInvoicePayments)
