# Generated by Django 5.2.4 on 2025-09-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("cms", "0002_alter_blockmedia_media_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image_posts",
                to="cms.blockmedia",
            ),
        ),
    ]
