# Generated by Django 5.2.4 on 2025-09-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
