# Generated by Django 5.2.4 on 2026-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategorytranslation",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tagtranslation",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
