# Generated by Django 5.2.4 on 2025-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_comment_author_name_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="no_comments",
            field=models.BooleanField(default=False),
        ),
    ]
