# Generated by Django 5.2.4 on 2025-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_no_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="may_be_obscene",
            field=models.BooleanField(default=False),
        ),
    ]
