# Generated by Django 5.2.4 on 2025-10-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_comment_may_be_obscene"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "permissions": [
                    ("manage_blog_categories", "Can manage blog categories")
                ],
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "permissions": [("manage_blog_comments", "Can manage blog comments")],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [("manage_blog_tags", "Can manage blog tags")],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
