# Generated by Django 5.2.4 on 2025-11-01 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blogcategory_options_alter_comment_options_and_more"),
        ("cms", "0017_alter_blockfilterpost_limit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "is_approved", "-created_at"],
                name="blog_commen_post_id_1f15d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="blog_post_author__418f7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-published_date", "-created_at"],
                name="blog_post_status_401223_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["category", "status", "-published_date"],
                name="blog_post_categor_0ea9a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-views_count"], name="blog_post_status_55c6cf_idx"
            ),
        ),
    ]
