# Generated by Django 5.2.4 on 2025-11-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment_blog_commen_post_id_1f15d9_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
