# Generated by Django 5.2.4 on 2025-11-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_blogcategory_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
