# Generated by Django 5.2.4 on 2025-09-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
