# Generated by Django 5.2.4 on 2025-09-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_delete_wallet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="business_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="client_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nit",
        ),
    ]
