# Generated by Django 5.2.4 on 2025-10-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_business_name_remove_user_client_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
