# Generated by Django 5.2.4 on 2025-10-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="fixed_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="fee",
            name="percentual_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
