# Generated by Django 5.2.4 on 2025-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_fee_fixed_fee_alter_fee_percentual_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="fixed_fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="fee",
            name="percentual_fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
