# Generated by Django 5.2.4 on 2025-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_fee_fixed_fee_alter_fee_percentual_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_delivery",
            field=models.BooleanField(default=False),
        ),
    ]
