# Generated by Django 5.2.4 on 2025-10-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_user_is_delivery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_delivery",
            new_name="is_deliver",
        ),
    ]
