# Generated by Django 5.2.4 on 2025-10-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_rename_is_delivery_user_is_deliver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="user/user_photo_default.png",
                null=True,
                upload_to="user/pics",
            ),
        ),
    ]
