# Generated by Django 5.2.4 on 2025-10-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_user_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_deliver",
            new_name="is_deliverer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="belong_to",
        ),
    ]
