# Generated by Django 5.2.4 on 2025-10-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_rename_is_deliver_user_is_deliverer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
