# Generated by Django 5.2.4 on 2025-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_user_whatsapp_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="whatsapp_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_chat_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
