# Generated by Django 5.2.4 on 2025-11-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0015_remove_user_whatsapp_verified_user_whatsapp_chat_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="user_user_phone_n_523d33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_deliverer", "is_active"],
                name="user_user_is_deli_95b978_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["newsletter", "is_active"], name="user_user_newslet_63d68e_idx"
            ),
        ),
    ]
