# Generated by Django 5.2.4 on 2025-11-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_user_user_user_phone_n_523d33_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventlog",
            options={
                "default_permissions": [],
                "ordering": ["-raised_date"],
                "verbose_name": "Event Log",
                "verbose_name_plural": "Event Logs",
            },
        ),
    ]
