# Generated by Django 5.2.4 on 2025-12-10 19:19

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_eventlog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                default="user/user_photo_default.png",
                force_format=None,
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[100, 100],
                upload_to="user/pics",
            ),
        ),
    ]
