# Generated by Django 5.2.4 on 2026-01-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_user", "Can manage user"),
                    ("manage_pos", "Can manage point of sale"),
                    ("manage_page", "Can manage page"),
                    ("manage_role", "Can manage role"),
                    ("show_all_boards", "Can show all boards"),
                    ("show_own_board", "Can show own board"),
                    ("show_all_orders", "Can show all orders"),
                    ("show_all_clients", "Can show all clients"),
                    ("show_availables_products", "Can show availables products"),
                ],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
