# Generated by Django 5.2.4 on 2026-01-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
