# Generated by Django 5.2.4 on 2026-01-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_fee_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nit_code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("empresa_estatal", "Empresa Estatal"),
                            ("mipyme", "MiPyme"),
                            ("tcp", "TCP"),
                        ],
                        default="empresa_estatal",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["-id"],
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
