# Generated by Django 5.2.4 on 2026-01-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [("manage_organization", "Can manage organization")],
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
    ]
