# Generated by Django 5.2.4 on 2026-01-16 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_alter_organization_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="user.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
