# Generated by Django 5.2.4 on 2026-02-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": [],
                "ordering": ["-id"],
                "permissions": [
                    ("manage_user", "Can manage user"),
                    ("manage_customer", "Can manage customer"),
                    ("show_customer_orders", "Can show customer orders"),
                    ("show_customer_wallet", "Can show customer wallet"),
                    ("show_customer_coupons", "Can show customer coupons"),
                    ("show_customer_unpaid_orders", "Can show customer unpaid orders"),
                    ("manage_pos", "Can manage point of sale"),
                    ("manage_page", "Can manage page"),
                    ("manage_role", "Can manage role"),
                    ("show_all_boards", "Can show all boards"),
                    ("show_own_board", "Can show own board"),
                    ("show_all_orders", "Can show all orders"),
                    ("show_all_clients", "Can show all clients"),
                    ("show_availables_products", "Can show availables products"),
                    (
                        "show_dashboards_conversion_rates",
                        "Can show conversion rates report",
                    ),
                    ("show_dashboards_unpaid_report", "Can show unpaid orders report"),
                    ("can_deliver_orders", "Can deliver orders"),
                ],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
