# Generated by Django 5.2.4 on 2026-02-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_user_id_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="id_number",
            new_name="dni",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
