# Generated by Django 5.2.4 on 2026-02-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_alter_user_email_user_unique_email_not_null"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_not_null",
        ),
    ]
